name: Demo Nginx CI

on:
  push:
    tags:
      - 'v*'

env:
   IMAGE_TAG: demonginx

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push images
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./.
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_TAG }}:${{ github.ref_name }}